# import 'package:gozy/graphql/reservation_fragment.graphql'

#Trips
query getAllReservation ($userType: String, $currentPage: Int, $dateFilter: String){
getAllReservation(userType: $userType, currentPage: $currentPage, dateFilter: $dateFilter){
result {
    ...reservationFragment
}
count
status
}
}



query contactSupport($message: String, $listId: Int, $reservationId: Int, $userType: String) {
  contactSupport(message: $message, listId: $listId, reservationId: $reservationId, userType: $userType) {
    result{
      userId
      email
      firstName
  	}
     status
      errorMessage
  }
}

mutation ReservationStatus(
        $threadId: Int!,
$content: String,
$type: String,
$startDate: String,
$endDate: String,
$personCapacity: Int,
$reservationId: Int,
$actionType: String,
$startTime: Float,
$endTime: Float
) {
reservationStatus:ReservationStatus(
        threadId: $threadId,
content: $content,
type: $type,
startDate: $startDate,
endDate: $endDate,
personCapacity: $personCapacity,
reservationId: $reservationId,
actionType: $actionType,
startTime: $startTime,
endTime: $endTime
) {
status
        errorMessage

}
}