// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
																		apiKey: "AIzaSyDBII_wKGUBy5_65y-bAuAsl8he6aZ_83g",
																		appId: "1:1043149604949:android:01efcd4eb29d5bfd88ecdc",
																		messagingSenderId: "1043149604949",
																		projectId: "gozy-8d3e0",
																		databaseURL: "null",
																		storageBucket: "gozy-8d3e0.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
								apiKey: "AIzaSyBhvzTnx_creSN-fGTGdwv9zumpaSES_7U",
								appId: "1:1043149604949:ios:09a3c8d5f1f1726c88ecdc",
								messagingSenderId: "1043149604949",
								projectId: "gozy-8d3e0",
								databaseURL: "null",
								storageBucket: "gozy-8d3e0.firebasestorage.app",
								androidClientId: "1043149604949-745jfv54jr0pdb7o81kf2smjvbqmq7bu.apps.googleusercontent.com",
								iosClientId: "1043149604949-86lc91uqlppnt8vrockjeb595ghnp3ah.apps.googleusercontent.com",
								iosBundleId: "com.gozy.app",
  );
}