# import 'package:gozy/graphql/base_listing_info_fragment.graphql'

#Create WishList Group
mutation CreateWishListGroup(
    $name: String!,
    $id: Int,
    $isPublic: String,
){
    CreateWishListGroup(
        name: $name,
        id: $id,
        isPublic: $isPublic
    ) {
        status
        errorMessage
        results {
            name
            isPublic
            id
        }
    }
}

#Get All WishList Group with pagination
query getAllWishListGroup($currentPage: Int){
    getAllWishListGroup(currentPage: $currentPage){
      status
      count
      errorMessage
      results {
        id
        name
        isPublic
        wishListCount
        wishListCover {
          id
          listId
          listData {
            ...viewListingShortFragment
           }
        }
        wishLists {
          listId
          listData {
         listPhotoName

          }
        }
  	  }
    }
}


#Create WishList
mutation CreateWishList(
    $listId: Int!,
    $wishListGroupId:Int,
    $eventKey:Boolean,
){
    CreateWishList(
        listId: $listId,
        wishListGroupId: $wishListGroupId,
        eventKey: $eventKey,
    ) {
        status
       errorMessage
    }
}

#Get WishList Group
query getWishListGroup ($id: Int!, $currentPage: Int){
    getWishListGroup(id: $id, currentPage: $currentPage){
        status
        errorMessage
        results {
            id
            name
            userId
            isPublic
            updatedAt
            wishListIds
            wishListCount
        	wishLists {
              id
              listId
              listData {
              ...viewListingShortFragment
              }
            }
        }
    }
}

#Delete WishList Group
mutation DeleteWishListGroup(
    $id: Int!,
){
    DeleteWishListGroup(
        id: $id
    ) {
        status
        errorMessage
    }
}

#Update WishList Group
mutation UpdateWishListGroup(
    $isPublic: Int,
    $id: Int!
){
    UpdateWishListGroup(
        isPublic: $isPublic,
        id: $id
    ) {
        status
        errorMessage
    }
}