# import 'package:gozy/graphql/listing_fragment.graphql'

# Similar Listing
query getSimilarListing (
    $lat: Float,
    $lng: Float,
    $listId: Int
) {
    getSimilarListing (
        listId: $listId,
        lat: $lat,
        lng: $lng
    ) {
       results {
        id
        ...viewListingShortFragment
        }
        status
    }
}

# Listing_Details
query viewListingDetails(
    $listId:Int!,
    $preview: Boolean
) {
    viewListing (
        listId:$listId,
        preview: $preview
    ) {
        results {
          id
          ...viewListingDetailsFragment
        }
        status
        errorMessage
    }
}

# Review
query getReviewsList(
    $listId: Int,
    $currentPage: Int,
    $hostId: String!
) {
    getReviews(
        listId: $listId,
        currentPage: $currentPage,
        hostId: $hostId
    ) {
results {
id
        isAdmin
reservationId
        listId
authorId
        userId
reviewContent
        rating
parentId
        automated
createdAt
        authorData{
        userId
        profileId
        firstName
        lastName
        picture
}
userData{
userId
        profileId
firstName
        lastName
picture
}
}
        status
        count
    }
}

# Date Availability
query dateAvailability($listId: Int!, $startDate: String!, $endDate: String!){
  dateAvailability(listId: $listId, startDate: $startDate, endDate: $endDate){
    results{
      blockedDates
    }
    status
  }
}

# Contact Host
mutation ContactHost($listId: Int!, $hostId: String!, $content: String!, $userId: String!, $type: String, $startDate: String!, $endDate: String!, $personCapacity: Int, $startTime: Float, $endTime: Float) {
createEnquiry:CreateEnquiry(listId: $listId, hostId: $hostId, userId: $userId, content: $content, type: $type, startDate: $startDate, endDate: $endDate, personCapacity: $personCapacity, startTime: $startTime, endTime: $endTime) {
status
        errorMessage
result {
id
        sentBy
content
        type
startDate
        endDate
startTime
        endTime
personCapacity
        createdAt
}
}
}

# ReportUser
mutation CreateReportUser($reporterId: String, $userId: String, $reportType: String, $profileId: Int, $reporterName:String){
createReportUser(reporterId: $reporterId, userId: $userId, reportType: $reportType, profileId: $profileId,reporterName:$reporterName) {
status
 errorMessage
}
}

# ReportList
query getAllReportType {
    getAllReportType {
                status
                errorMessage
                results {
                    id
                    reportType
                    reportContent
          }
        }
}