# import 'package:gozy/graphql/listing_fragment.graphql'

# Manage Listing
query ManageListings($currentPage: Int, $requestType: String) {
      ManageListings(currentPage: $currentPage, requestType: $requestType){
       results {
        id
        ...viewListingDetailsFragment
        }
        count
        status
        errorMessage
    }
}

query listBlockedDates($listId: Int!){
    getListBlockedDates (listId: $listId){
    results {
        blockedDates {
        blockedDates
        reservationId
        listId
        }
    }
        status
        errorMessage
    }
}



mutation UpdateListBlockedDates(
        $listId: Int!,
        $blockedDates: [String]
) {
updateListBlockedDates:UpdateListBlockedDates (
        listId: $listId,
        blockedDates: $blockedDates)
{
status
}
}

 #DeleteList
 mutation RemoveListing($listId:Int!) {
           RemoveListing (listId:$listId) {
           results{
             id
             name
           }
           status
           errorMessage
          }
}



#Delete List Photos
mutation RemoveMultiPhotos(
        $photos: String,
) {
removeMultiPhotos: RemoveMultiPhotos (
        photos: $photos) {
status
        errorMessage
}
}

#Listing Special Price
query getListingSpecialPrice($listId: Int!){
getListingSpecialPrice (listId: $listId){
results {
id
        listId
reservationId
        blockedDates
calendarStatus
        isSpecialPrice
listCurrency
}
status
        errorMessage
}
}

#UpdateSpecialPrice
mutation UpdateSpecialPrice(
        $listId: Int!,
$blockedDates: [String],
$calendarStatus: String,
$isSpecialPrice: Float
) {
updateSpecialPrice: UpdateSpecialPrice (
        listId: $listId,
blockedDates: $blockedDates,
calendarStatus: $calendarStatus,
isSpecialPrice: $isSpecialPrice
)
{
status
        errorMessage
}
}